### PR TITLE
Make intake

### PR DESCRIPTION
**Pull request by team6101**
# Description

made it so the intake can run

# Checklist before marking this PR as ready for review

-   [x] All the PR checks are passing (you see the green checkmark)
-   [x] I have written comments on the PR where reviewers may have questions

### CODE REVIEW

**Review by Nanosplitter — CHANGES_REQUESTED** [review]
All these changes seem to be in the PR I just reviewed

**Comment by team6101** [comment]
we forgot to pull from main before writing different code

**Review by team6101 — COMMENTED** [review]
we want to push things in the right order

**Review by Alex-Dog — APPROVED** [review]
We don't know how to fix the issue after it has already happened, so we are just gonna merge this.

**Pull request merged**
